//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppleWatch.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AppleWatchEntities : DbContext
    {
        public AppleWatchEntities()
            : base("name=AppleWatchEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Genuine> Genuines { get; set; }
        public virtual DbSet<Promotion> Promotions { get; set; }
        public virtual DbSet<PromotionApplication> PromotionApplications { get; set; }
        public virtual DbSet<SaleOff> SaleOffs { get; set; }
        public virtual DbSet<Series> Series { get; set; }
        public virtual DbSet<Strap> Straps { get; set; }
        public virtual DbSet<Watch> Watches { get; set; }
    }
}
