//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppleWatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Watch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Watch()
        {
            this.PromotionApplications = new HashSet<PromotionApplication>();
            this.SaleOffs = new HashSet<SaleOff>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public int SeriesId { get; set; }
        public int StrapId { get; set; }
        public Nullable<int> GenuineId { get; set; }
        public bool IsAuthorisedReseller { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Genuine Genuine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PromotionApplication> PromotionApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleOff> SaleOffs { get; set; }
        public virtual Series Series { get; set; }
        public virtual Strap Strap { get; set; }
    }
}
